name: spajam_24_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.3
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1
  flutter_gen_runner: ^5.6.0

flutter_gen:
  output: lib/gen
  lineLength: 80

flutter:
  uses-material-design: true

  assets:
    - assets/fire.gif
    - assets/no_fire.png
    - assets/launch_icon.png
